### PR TITLE
disable alpha features

### PR DESCRIPTION
**Pull request by boardthatpowder**
Alpha features may not be enabled by default, or available at all in some distributions.

### CODE REVIEW

**Review by medyagh — CHANGES_REQUESTED** [review]
Thanks for the contribution, That is actually a great idea to be able to disable alpha features ! could you please make the PR to add the config variables to the libs ? then test them together ?

**Comment by medyagh** [comment]
@boardthatpowder please add the latest k8guardlibs SHA to the glide yaml, u can grab the latest SHA from https://github.com/k8guard/k8guardlibs/commits/master

**Review by medyagh — CHANGES_REQUESTED** [review]
@boardthatpowder what was the reason you renamed the hooks/pre-commit → hooks/pre-commit-disabled ?

**Comment by boardthatpowder** [comment]
Sorry, only just seen this.  Did not mean to check in changes to hooks/pre-commit.  The pre-commit kept failing via IDE, but was fine from command line.  Could not figure out what was going wrong so temporarily disabled it.  Will revert that.

**Comment by medyagh** [comment]
@boardthatpowder sounds good, let me know when you commit the new changes.

**Comment by boardthatpowder** [comment]
Done, ready for review again.

**Comment by medyagh** [comment]
@boardthatpowder  looks good to me. thanks 👍

**Review by medyagh — APPROVED** [review]
thanks for the changes and contributing.

**Pull request merged**
